// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN4XVpE1i9qzZ-cYop5oe5ku5EtbaUgYc',
    appId: '1:385530081520:web:bbb03b586a0ce9a02b1235',
    messagingSenderId: '385530081520',
    projectId: 'empreenda-ab21b',
    authDomain: 'empreenda-ab21b.firebaseapp.com',
    storageBucket: 'empreenda-ab21b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlD-kFezD8qY8zgw5mz6DucLHqPgsq8sc',
    appId: '1:385530081520:android:482ef4a625ad3cf92b1235',
    messagingSenderId: '385530081520',
    projectId: 'empreenda-ab21b',
    storageBucket: 'empreenda-ab21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBlF_kRtx6kDedn9_OgiTb4bCbEePn3E',
    appId: '1:385530081520:ios:e01c6058d2829ece2b1235',
    messagingSenderId: '385530081520',
    projectId: 'empreenda-ab21b',
    storageBucket: 'empreenda-ab21b.firebasestorage.app',
    iosBundleId: 'com.example.emartSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBlF_kRtx6kDedn9_OgiTb4bCbEePn3E',
    appId: '1:385530081520:ios:e01c6058d2829ece2b1235',
    messagingSenderId: '385530081520',
    projectId: 'empreenda-ab21b',
    storageBucket: 'empreenda-ab21b.firebasestorage.app',
    iosBundleId: 'com.example.emartSeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN4XVpE1i9qzZ-cYop5oe5ku5EtbaUgYc',
    appId: '1:385530081520:web:70a8ede7f8afbfff2b1235',
    messagingSenderId: '385530081520',
    projectId: 'empreenda-ab21b',
    authDomain: 'empreenda-ab21b.firebaseapp.com',
    storageBucket: 'empreenda-ab21b.firebasestorage.app',
  );
}
